[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sim"
version = "0.1.0"
description = "A short description of the project"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "spicelib",
    "PySpice",
    "pandas"
]

[project.optional-dependencies]
dev = [
    "ruff",
]
