---
name: CI

on:
  pull_request:
  merge_group:


defaults:
  run:
    working-directory: ./sim

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install package
        run: pip3 install .[dev]

      - name: Ruff lint
        run: ruff check

  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install package
        run: pip3 install .[dev]

      - name: Ruff format
        run: ruff format --check


  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install build package
        run: pip3 install build

      - name: Build package
        run: python3 -m build .

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          name: python-package-distributions
          path: dist/

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install package
        run: pip3 install .
